on:
  push:
    branches:
      - main
      - build-dev

jobs:
  run_build_script:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install Python dependencies
        run: pip install -r requirements.txt
        working-directory: build 
      - name: run build script
        run: python3 build.py


