on:
  push:
    branches:
      - main

jobs:
  run_build_script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Python File
        run: python build/build.py
