on:
  push:
    branches:
      - main
      - build-dev

jobs:
  run_build_script:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Copy sketches to build dir
        run: cp -r sketches build/
      - name: Install Python dependencies
        run: pip install -r requirements.txt
        working-directory: build 
      - name: run build script
        run: python3 build.py --out-dir html sketches
        working-directory: build
      - name: TEST - list directories
        run: ls -R
      - name: copy the sketchees to the out directory
        run: cp -r sketches html/sketches
        working-directory: build
      - name: TEST - list directories again
        run: ls -R
      - name: TEST - copy trees to index.html for testing
        run: cp html/trees.html html/index.html
        working-directory: build
      - name: TEST - list directories again again
        run: ls -R
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v2.0.0
        with:
          # Artifact name
          # name: # optional, default is github-pages
          # Path of the directory containing the static assets.
          path: build/html # default is _site/
          # Duration after which artifact will expire in days.
          retention-days: # optional, default is 1
      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v1.2.9
